### ISSUE TITLE
Typos in the Hadoop intro wiki page

### ISSUE THREAD

**Issue by precabal** [InsightDataScience/data-engineering-ecosystem#3]
Hi, while following the Hadoop Intro guide, I found the following typos:

A. under the configure core-site.xml section, there is a backslash missing from the closing xml tag for the property:

```
<property> 
   <name>fs.defaultFS</name>
   <value>hdfs://namenode-public-dns:9000</value>
<property>
``` 

B. under the configure core-site.xml and configure yarn-site.xml sections, it refers to adding these properties to the respective files, between the (blank) tags. it should read `<configuration>` in both cases.

**Comment by danielblazevski** [comment]
Thanks @precabal I fixed this!
